[build]
  publish = "."
  command = "# No build command"

# Asegurarse de que todos los archivos se incluyan en el despliegue
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false

# Configuración para Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Configuración para Netlify CMS
[[redirects]]
  from = "/netlify-cms/*"
  to = "/netlify-cms/index.html"
  status = 200

# Configuración para la API de Git Gateway
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"

# Configuración de caché para archivos JSON
[[headers]]
  for = "/data/*"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    pragma = "no-cache"
    expires = "0"
