[build]
  publish = "."
  command = "# No build command"

# Asegurarse de que todos los archivos se incluyan en el despliegue
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false

# Configuraci贸n para Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Configuraci贸n para Netlify CMS
[[redirects]]
  from = "/netlify-cms/*"
  to = "/netlify-cms/index.html"
  status = 200

# Configuraci贸n para la API de Git Gateway
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self'"
    X-Content-Type-Options = "nosniff"

# Configuraci贸n especial para archivos HTML en activities
[[headers]]
  for = "/activities/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-ancestors 'self';"
    Access-Control-Allow-Origin = "*"
